version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQLDB_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - DATASOURCE_URL=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false
      - DATASOURCE_USER=${MYSQLDB_USER}
      - DATASOURCE_PASSWORD=${MYSQLDB_PASSWORD}
      - DATASOURCE_DIALECT=${DATABASE_DIALECT}
      - DATASOURCE_DDL_MANAGEMENT_POLICY=${DATABASE_DDL_POLICY}
      - SPRING_DOCKER_PORT=${SPRING_DOCKER_PORT}
    volumes:
      - .m2:/root/.m2
      - .:/app
      
    stdin_open: true
    tty: true

volumes:
  db:
